name: presence
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.0.5 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  firebase_core: 2.15.0
  firebase_auth: 4.7.1
  cloud_firestore: 4.8.3
  firebase_storage: 11.2.5
  flutter: 
    sdk: flutter
  cached_network_image: ^3.2.3

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

